<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net11.0</TargetFramework>
    <RuntimeIdentifier>win-x64</RuntimeIdentifier>
    <PublishAot>true</PublishAot>
    <EventSourceSupport>false</EventSourceSupport>
    <InvariantGlobalization>true</InvariantGlobalization>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
  </PropertyGroup>
  <ItemGroup>
    <Compile Include="../../External/AudioPlayer/**/*.cs"
             Exclude="../../External/AudioPlayer/Program.cs;../../External/AudioPlayer/obj/**/*.cs;../../External/AudioPlayer/bin/**/*.cs" />
    <ProjectReference Include="../../External/BassPlayerIpc.Shared/BassPlayerIpc.Shared.csproj" />
    <PackageReference Include="FFmpeg.AutoGen" Version="9.0.1.1" />
    <None Include="../../Libraries/FFmpeg/x64/*.dll;../../Libraries/WavPack/x64/wavpackdll.dll"
          Link="%(Filename)%(Extension)" CopyToOutputDirectory="PreserveNewest" CopyToPublishDirectory="PreserveNewest" />
  </ItemGroup>
</Project>
